language: go
os: linux
sudo: required

go:
  - 1.x

before_install:
  - sudo apt-get install -y libvirt-dev
install:
  - echo "Don't run anything."
script:
  - make test
after_success:
  - bash <(curl -s https://codecov.io/bash)
